spring:
  application:
    name: eureka-server
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}

# Valores por defecto usados solo si el Config Server no responde
server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
